CREATE DATABASE bookstore;
CREATE TABLE author(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), birth_date DATE);
CREATE TABLE book(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, title VARCHAR(100), description VARCHAR(255), release_date DATE, author_id INT, FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE CASCADE)
