# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_USER: kiki
      MYSQL_PASSWORD: 1234
    # (this is just an example, not intended to be a production configuration)
    ports:
      - "3306:3306"
      - "33060:33060"

